# Change these first
owner: C21coastsh # Your GitHub organization or username, where this repository lives
repo: ws-ut # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 * * * *"

sites:
  - name: VPMadonna
    url: https://c21coasttocoast.mobi/MADONNASTEINLAGE
  - name: C21CoasttoCoast
    url: https://www.c21coasttocoast.com/
    maxResponseTime: 8000
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
  - name: Fl Gulf Beach RE
    url: https://www.floridagulfbeachrealty.com/
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /ws-ut
  logoUrl: https://storage.googleapis.com/idx-acnt-gs.ihouseprd.com/AR1191858/file_manager/Branding/C21%20favicon.png
  name: C21Coastsh
  introTitle: "**WebSite-Upptime** is the uptime monitor and status page for C21CtoC, powered by GitHub."
  introMessage: This status page which uses **real-time** data from our [GitHub repository](https://github.com/C21coastsh/ws-ut).
  skipDeleteIssues: true
  theme: dark
  navbar:
    - title: Status
      href: /ws-ut
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
